services:
  - type: web
    name: lestnitsa-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 65
    envVars:
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true
