services:
  - type: web
    name: @superlestnica_bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 65
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0  # Фиксируем Python 3.11 вместо 3.13
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        value: "@superlestnica_bot"
      - key: RENDER_EXTERNAL_URL
        sync: false
